### ISSUE TITLE
Serialization issues with xarrays containing variables of different dimensionality

### ISSUE THREAD

**Issue by jsignell** [ContinuumIO/intake-xarray#19]
Here are some different netcdf imports that don't work properly. I don't think it is quite the same as what Mike was referencing, but just to keep a record. 

```python
intake.open_netcdf('https://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/noaaglobaltemp/air.mon.anom.1971-2000.nc', 
                   chunks={'lat': 1, 'lon': 1, 'time': 1},  xarray_kwargs={'decode_times': False}).to_dask()

intake.open_netcdf('http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.reanalysis.dailyavgs/surface_gauss/air.2m.gauss.2018.nc', 
                   chunks={'time': 1, 'lat': 1, 'lon': 1}).to_dask()
```

**Comment by martindurant** [comment]
Ref: #18

**Comment by jsignell** [comment]
Here is an example of the one Mike was talking about. The issue is that the second file has 15m resolution vs 30 in the first so there are twice as many of the x and y coordinates.

With catalog:
```yaml
sources:
  google_landsat_band:
    driver: rasterio
    parameters:
      path:
        description: landsat path
        type: int
      row:
        description: landsat row
        type: int
      pid:
        description: landsat file id
        type: str
    args: 
      urlpath: 
       - https://storage.googleapis.com/gcp-public-data-landsat/LC08/01/{{ '%03d' % path }}/{{ '%03d' % row }}/{{ pid }}/{{ pid }}_B1.TIF
       - https://storage.googleapis.com/gcp-public-data-landsat/LC08/01/{{ '%03d' % path }}/{{ '%03d' % row }}/{{ pid }}/{{ pid }}_B8.TIF
      chunks:
        band: 1
        x: 256
        y: 256
```

Try to open:
```python
path = 14
row = 32
pid = 'LC08_L1TP_014032_20160727_20170222_01_T1'
cat.google_landsat_band(path=path, row=row, pid=pid).to_dask()
```

Error like:
```txt
/Users/jsignell/xarray/xarray/backends/zarr.py in _determine_zarr_chunks(enc_chunks, var_chunks, ndim)
     82                 "Zarr requires uniform chunk sizes excpet for final chunk."
     83                 " Variable %r has incompatible chunks. Consider "
---> 84                 "rechunking using `chunk()`." % (var_chunks,))
     85         if any((chunks[0] < chunks[-1]) for chunks in var_chunks):
     86             raise ValueError(

ValueError: Zarr requires uniform chunk sizes excpet for final chunk. Variable ((1, 1), (1,), (125, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256, 1, 255, 256), (256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 121)) has incompatible chunks. Consider rechunking using `chunk()`.
```
