### ISSUE TITLE
accept a list of netcdf paths

### ISSUE THREAD

**Issue by rabernat** [ContinuumIO/intake-xarray#30]
Xarray's [`open_mfdataset`](http://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html) function accepts a wildcard (passed to glob) OR an explicit list of paths to open.

Intake, however, currently only supports the wildcard option
https://github.com/ContinuumIO/intake-xarray/blob/4985727425b2b6fa75237d40f3163b404d926dc0/intake_xarray/netcdf.py#L29-L31

What I would like is to have a catalog like this:
```yaml
sources:
  some_dataset:
    driver: netcdf
    args:
      urlpath:
        - file1.nc
        - file2.nc
```

and have this get translated as `xr.open_mfdataset(['file1.nc', 'file2.nc'])`.

This is both more urgent (to me!) and more doable than #29.
